# Generated by Django 6.0.1 on 2026-02-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=False, help_text='Allow others to see your full phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (without @)', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp phone number', max_length=20),
        ),
    ]
