# Generated by Django 6.0.1 on 2026-02-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenancyapplication',
            name='landlord_reply',
            field=models.TextField(blank=True, help_text="Landlord's reply to the tenant's application"),
        ),
    ]
