# Generated by Django 6.0.1 on 2026-02-25 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenancyapplication_landlord_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this file', max_length=200)),
                ('file', models.FileField(upload_to='tenant_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tenancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenancy.tenancy')),
            ],
            options={
                'db_table': 'tenant_documents',
                'ordering': ['id'],
            },
        ),
    ]
