# Generated by Django 6.0.1 on 2026-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_period',
            field=models.IntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year')], default=12, help_text='Rent payment period in months'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
