# Generated by Django 6.0.1 on 2026-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_rent_period_alter_property_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description for marketplace listing'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Visible on public marketplace'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale'), ('land', 'Land')], default='rent', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('flat', 'Flat'), ('shop', 'Shop/Commercial'), ('land', 'Land'), ('other', 'Other')], default='house', max_length=20),
        ),
    ]
