# Generated by Django 6.0.1 on 2026-02-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_description_property_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale'), ('shortlet', 'Shortlet'), ('land', 'Land')], default='rent', max_length=10),
        ),
    ]
