# Generated by Django 6.0.1 on 2026-02-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.ImageField(blank=True, help_text='Property photo', null=True, upload_to='properties/'),
        ),
    ]
