# Generated by Django 6.0.1 on 2026-02-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='shortlet_end',
            field=models.DateField(blank=True, help_text='Check-out date for shortlet listings', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='shortlet_start',
            field=models.DateField(blank=True, help_text='Check-in date for shortlet listings', null=True),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='properties.property')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
