# Generated by Django 6.0.1 on 2026-01-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='viewed_by_landlord',
            field=models.BooleanField(default=False),
        ),
    ]
